/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.0 		*/
/*  Created On : 03-1月-2020 09:53:51 				*/
/*  DBMS       : MySql 						*/
/* ---------------------------------------------------- */

SET FOREIGN_KEY_CHECKS=0
; 
/* Drop Tables */

DROP TABLE IF EXISTS `Commodity` CASCADE
;

DROP TABLE IF EXISTS `Customer` CASCADE
;

DROP TABLE IF EXISTS `Order` CASCADE
;

DROP TABLE IF EXISTS `OrderDetail` CASCADE
;

DROP TABLE IF EXISTS `Stock` CASCADE
;

/* Create Tables */

CREATE TABLE `Commodity`
(
	`commodityId` BIGINT NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(50) NULL,
	`price` DECIMAL(10,4) NULL,
	`color` VARCHAR(50) NULL,
	CONSTRAINT `PK_Commodity` PRIMARY KEY (`commodityId` ASC)
)

;

CREATE TABLE `Customer`
(
	`customerId` BIGINT NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(50) NULL,
	`phone` VARCHAR(50) NULL,
	`sex` VARCHAR(50) NULL,
	CONSTRAINT `PK_Customer` PRIMARY KEY (`customerId` ASC)
)

;

CREATE TABLE `Order`
(
	`orderId` BIGINT NOT NULL AUTO_INCREMENT,
	`customerId` BIGINT NOT NULL,
	`status` INT NOT NULL DEFAULT 0,
	`totalSum` DECIMAL(10,4) NOT NULL,
	`createTime` DATETIME NOT NULL,
	CONSTRAINT `PK_Order` PRIMARY KEY (`orderId` ASC)
)

;

CREATE TABLE `OrderDetail`
(
	`ord` BIGINT NOT NULL,
	`orderId` BIGINT NOT NULL,
	`commodity` BIGINT NOT NULL,
	`count` DECIMAL(10,4) NOT NULL,
	CONSTRAINT `PK_OrderDetail` PRIMARY KEY (`ord` ASC)
)

;

CREATE TABLE `Stock`
(
	`ord` BIGINT NOT NULL AUTO_INCREMENT,
	`commodity` BIGINT NOT NULL,
	`stockNum` DECIMAL(10,4) NOT NULL,
	`units` VARCHAR(50) NULL,
	CONSTRAINT `PK_Stock` PRIMARY KEY (`ord` ASC)
)

;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE `Order` 
 ADD INDEX `IXFK_Order_Customer` (`customerId` ASC)
;

ALTER TABLE `OrderDetail` 
 ADD INDEX `IXFK_OrderDetail_Commodity` (`commodity` ASC)
;

ALTER TABLE `OrderDetail` 
 ADD INDEX `IXFK_OrderDetail_Order` (`orderId` ASC)
;

ALTER TABLE `Stock` 
 ADD INDEX `IXFK_Stock_Commodity` (`commodity` ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE `Order` 
 ADD CONSTRAINT `FK_Order_Customer`
	FOREIGN KEY (`customerId`) REFERENCES `Customer` (`customerId`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `OrderDetail` 
 ADD CONSTRAINT `FK_OrderDetail_Commodity`
	FOREIGN KEY (`commodity`) REFERENCES `Commodity` (`commodityId`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `OrderDetail` 
 ADD CONSTRAINT `FK_OrderDetail_Order`
	FOREIGN KEY (`orderId`) REFERENCES `Order` (`orderId`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `Stock` 
 ADD CONSTRAINT `FK_Stock_Commodity`
	FOREIGN KEY (`commodity`) REFERENCES `Commodity` (`commodityId`) ON DELETE Restrict ON UPDATE Restrict
;

SET FOREIGN_KEY_CHECKS=1
; 
